#!/usr/bin/env php
<?php

$file = __DIR__;
if (file_exists($file = __DIR__ . "/../../autoload.php")) {
  /** @noinspection PhpIncludeInspection */
  require $file;
}
else if (file_exists($file = __DIR__ . "/vendor/autoload.php")) {
  /** @noinspection PhpIncludeInspection */
  require $file;
}
else {
  die("Can't find autoload.php");
}

(new Yaklass\TaskRunner\App())->run();

